name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: dashboard-front/package-lock.json
      - name: Build to static site
        run: cd dashboard-front && npm i && npm run build
      - name: Build and Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          workdir: dashboard-front
          name: ${{secrets.DOCKER_USERNAME}}/scut-monitoring-system-front
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # - name: Cache deps
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14
      #     cache: 'npm'
      #     cache-dependency-path: dashboard-back/package-lock.json
      - name: Build and Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          workdir: dashboard-back
          name: ${{secrets.DOCKER_USERNAME}}/scut-monitoring-system-back
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
  # deploy-to-server:
  #   runs-on: ubuntu-latest
  #   needs: [build-frontend, build-backend]
  #   steps:
  #     - name: Deploying to test server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: 22
  #         script: cd ~/SCUT-monitoring-system && sudo docker compose down && sudo docker compose pull && sudo docker compose up -d
  #     - name: Send notification
  #       run: curl -sSL https://sctapi.ftqq.com/${{ secrets.NOTIFICATION_KEY }}.send?title=服务部署完成
