name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-fe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build ./dashboard-front --tag scut-monitoring-system
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        workdir: ${{ PWD }}/dashboard-front
        name: ${{ secrets.DOCKER_USERNAME }}/scut-monitoring-system
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

