name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build and Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          workdir: dashboard-front
          name: ${{secrets.DOCKER_USERNAME}}/scut-monitoring-system-front
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build and Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          workdir: dashboard-back
          name: ${{secrets.DOCKER_USERNAME}}/scut-monitoring-system-back
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
